#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "Running installers..."

# If we're on a Mac, let's install and setup Homebrew.
# Make sure Homebrew is installed first
if [ "$(uname -s)" == "Darwin" ]
then
  echo "Installing Homebrew and packages"
  sh -c homebrew/brew-install.sh
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
